---
format: gfm
editor: visual
---

The goal of this repository is to do some light pre-processing to above-ground biomass data products and save them to the "snow" server in a common format.

Preprocessing steps to be done:

-   Name all layers appropriately

    -   If they are years, use the year (e.g. `"2005"`)

    -   If they represent a time range, use the time range (e.g. `"2005-2010"` or `"2009, 2012-2014"`)

    -   ❔If they are something other than AGB, append that to the year (e.g. `"2005_SD"` , `"2005_MEAN"`

-   Convert to units of Mg/ha

-   ❔Project to the same CRS

-   ❔Rasterize vector products

-   ❔Merge tiles into a single file

## Example

In `R/` there is a collection of `clean_*()` functions defined.
One of the simpler ones is for the Xu et al. dataset:

``` r
# Function has arguments for input and output path.  Input might be a directory in the case of multiple tiles
clean_xu <- function(
    input = "/Volumes/moore/Xu/test10a_cd_ab_pred_corr_2000_2019_v2.tif", 
    output = "/Volumes/moore/AGB_cleaned/xu.tif"
) {
  # Read in file(s)
  xu_agb_raw <- terra::rast(input) 
  # Do any necessary conversions or subsetting
  xu_agb <- xu_agb_raw * 2.2 
  # Add metadata including layer names
  units(xu_agb) <- "Mg/ha"
  varnames(xu_agb) <- "AGB"
  names(xu_agb) <- 2000:2019
  
  # Write to COG
  terra::writeRaster(xu_agb, output, filetype = "COG", overwrite = TRUE)
  # Return output path
  output
}
```

If you have snow mounted to `/Volumes/moore/` then all you need to do is run `clean_xu()` to read in the downloaded raw data, do the processing, and save it out as a COG to `AGB_cleaned/xu.tif`.

::: callout-note
This will actually write two files, `xu.tiff` and a "sidecar" file `xu.tiff.aux.json` containing some metadata (just the units in this example).
`terra::rast("path/to/xu.tiff")` will automatically also read in the sidecar file if it is in the same directory.
:::

Eventually, these functions may become part of a `targets` pipeline that will only re-run the pre-processing function if there have been changes in the function or the raw data file(s).
